### ISSUE TITLE
Hostname/IP doesn't match certificate's altnames

### ISSUE THREAD

**Issue by rick4470** [rabchev/brackets-server#11]
On startup of the server, I get the following ERROR.

```
➜  jsecademy git:(master) ✗ sudo brackets --port 80 --proj-dir /var/www --supp-dir /var/brackets

  listening on port 80


events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Hostname/IP doesn't match certificate's altnames
    at SecurePair.<anonymous> (tls.js:1379:23)
    at SecurePair.EventEmitter.emit (events.js:92:17)
    at SecurePair.maybeInitFinished (tls.js:982:10)
    at CleartextStream.read [as _read] (tls.js:469:13)
    at CleartextStream.Readable.read (_stream_readable.js:320:10)
    at EncryptedStream.write [as _write] (tls.js:366:25)
    at doWrite (_stream_writable.js:221:10)
    at writeOrBuffer (_stream_writable.js:211:5)
    at EncryptedStream.Writable.write (_stream_writable.js:180:11)
    at write (_stream_readable.js:583:24)
```

**Comment by rick4470** [comment]
Looks like this is a bigger issue, than I thought.

Work around

```
NODE_TLS_REJECT_UNAUTHORIZED=0 brackets --port 80 --proj-dir /var/www --supp-dir /var/brackets
```

Source https://github.com/chilts/awssum/issues/164
